# Generated by Django 3.0.4 on 2020-04-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split_bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='split_num',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='full_bill',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(default=None, max_length=50)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='split_bill.Bill')),
            ],
        ),
    ]
