# Generated by Django 3.0.4 on 2020-04-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split_bill', '0002_auto_20200406_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PersonBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbill', models.DecimalField(decimal_places=2, max_digits=6)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='split_bill.Person')),
            ],
        ),
    ]
