# Generated by Django 3.0.4 on 2020-04-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_bill', '0004_auto_20200410_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.RenameField(
            model_name='personbill',
            old_name='pbill',
            new_name='person_partbill',
        ),
    ]
